import '../../e2e/loginPage/loginPageDefaultValidation.cy'
//import 'cypress/e2e/createPatient/createPatient.cy.js'
//import '../../e2e/createPatient/createPatient.cy'
//import '../../e2e/appointment/appointment.cy'
import '../../e2e/createPatient/createPatient.cy'